# Generated by Django 5.2.8 on 2025-11-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('item_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos', to='inventario.item')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
